workflows:
  debug-build:
    name: Debug & Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - development

    scripts:
      - name: Clean and install dependencies
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod repo update --silent
          pod install --repo-update
          cd ..

      # 👇 Android Release APK
      - name: Build Android Release
        script: flutter build apk --release

      # 👇 iOS Debug (Simulator فقط)
      - name: Build iOS Debug (Simulator)
        script: flutter build ios --debug --no-codesign

      # 👇 iOS Release (IPA للتوزيع اليدوي/TestFlight لاحقاً)
      - name: Build iOS Release IPA
        script: flutter build ipa --release --no-codesign

    artifacts:
      # Android APK
      - build/app/outputs/flutter-apk/app-release.apk

      # iOS Simulator app
      - build/ios/iphonesimulator/*.app

      # iOS Release IPA
      - build/ios/ipa/*.ipa
