workflows:
  debug-build:
    name: Debug Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Install iOS dependencies (CocoaPods)
        script: |
          set -e # Stop on first error
          cd ios
          pod repo update
          pod install
      - name: Build Flutter App (Android)
        script: flutter build apk --debug
      - name: Build Flutter App (iOS)
        script: flutter build ios --debug --no-codesigning
    artifacts:
      - build/app/outputs/apk/debug/*.apk
      - build/ios/iphonesimulator/*.app
    publishing:
      email:
        recipients:
          - your_email@example.com # <-- غيّر هذا إلى إيميلك إذا لم تكن قد فعلت
