# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_application_path = '../'
  eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')), binding)

  # ✅ ما عاد يوقف البناء إذا ما لقى Generated.xcconfig
  generated_xcode_build_settings_path = File.join(flutter_application_path, 'Flutter', 'Generated.xcconfig')
  if File.exist?(generated_xcode_build_settings_path)
    puts "Including Generated.xcconfig"
  else
    puts "⚠️ Skipping Generated.xcconfig (will be generated later by Flutter)"
  end
end
